// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  alternate_grid: defineAsyncComponent(
    () => import("./AlternateGrid/index.vue"),
  ),
  article_title: defineAsyncComponent(
    () => import("./ArticleContent/index.vue"),
  ),
  navbar: defineAsyncComponent(() => import("./Navbar/index.vue")),
});
